Keyboard.println("notepad.exe");    //打开记事本
  delay(500);
  Keyboard.println("                                   $$$$ ");
  delay(500);
  Keyboard.println("                               $$         $$");
  Keyboard.println("                               $$         $$");
  Keyboard.println("                               $$         $$");
  Keyboard.println("                               $$         $$");
  Keyboard.println("                               $$         $$");
  Keyboard.println("                               $$         $$");
  Keyboard.println("                        $$$$$$         $$$$$$");
  Keyboard.println("   $$$$$$     $$         $$         $$        $$$$");
  Keyboard.println("   $$         $$$$         $$         $$        $$    $$");
  Keyboard.println("   $$             $$         $$         $$        $$        $$");
  Keyboard.println("        $$        $$                                 $$         $$");
  Keyboard.println("          $$$    $$                                              $$");
  Keyboard.println("            $$                                                      $$");
  Keyboard.println("              $$$                                                  $$");
  Keyboard.println("                $$                                                  $$");
  Keyboard.println("                  $$$                                              $$");
  Keyboard.println("                    $$                                          $$$");
  Keyboard.println("                      $$$                                      $$");
  Keyboard.println("                        $$                                      $$");
  Keyboard.println("                          $$$                              $$$");
  Keyboard.println("                            $$                              $$");
  Keyboard.println("                            $$$$$$$$$$$$$$$$$$$$");
  delay(500);
